### ISSUE TITLE
database/things/* errata discussion

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/pldb#92] opened 2022-09-10 11:04 UTC
alfred.pldb:
https://medium.com/@nikitavoloboev/writing-alfred-workflows-in-go-2a44f62dc432
References an IDE for mac users

alcor.pldb: 
Seemed to have copy pasted a few extra sentences from Wikipedia, in the summary section.

algobox.pldb:
Wikipedia page https://en.wikipedia.org/wiki/Algoboxn does not seem to exist. There are no other links.

database/things/alpha-programming-language.pldb and database/things/alpha.pldb :
Seem to be duplicates: Each file contains new information not present in the other.

**Comment by SRS-WRKS** [comment] 2022-09-22 05:02
database/things/bistro-programming-language.pldb:
The only reference page referring to wikipedia (https://en.wikipedia.org/wiki/Bistro_%28programming_language%29) Does not seem to exist anymore.

**Comment by breck7** [comment] 2022-09-22 05:33
Thanks! Feel free to send a Pull Request that you think is best and I can review (Or I can take a look in a little bit).

**Comment by SRS-WRKS** [comment] 2022-09-22 05:35
@breck7 : I will look into it after i finish the current issue. Too many tasks at a time would decrease accuracy of "grunt work" in my experience.

**Comment by adriantintpilver** [comment] 2022-09-30 13:47
Hello!

The idea of this issues is to unify the information of the duplicate entries? like for example: ciao-programming-language and ciao
Leaving only one record in "things" that has the unified information of the two records?

That would be the plan for each of the cases named in this issue?

Thank you so much!

**Comment by breck7** [comment] 2022-09-30 13:49
Yes @adriantintpilver !

**Comment by adriantintpilver** [comment] 2022-09-30 13:54
perfect. I will be working on this issue.
I understand that part of the task is to investigate the data and understand which is the real one, right?
For example, in the same case of CIAO there is a difference of 29 years between what one entry says and what the other says about the appearance date "appeared 2013" vs "appeared 1984".
There are other such discrepancies in the data.

**Comment by adriantintpilver** [comment] 2022-09-30 17:12
Question! In the event that we only find content in other languages and there is nothing in English?
This is the case of ALGOBOX, there is nothing in English, it is a French educational software and there is Wikipedia in French (https://fr.wikipedia.org/wiki/Algobox) and other pages in that language (https://www.xm1math.net/algobox/).

What do we do in these cases??
My proposal would be to translate a summary of the sentences into English so that there is something in English on our site and leave the links in the original language. what do you think?

**Comment by breck7** [comment] 2022-09-30 17:13
@adriantintpilver great question. maybe we can find someone who speaks french who could update that entry?

**Comment by breck7** [comment] 2022-09-30 17:14
@Puumanamana could you take a glance at https://build.pldb.com/edit/algobox and see if we're missing anything important?

**Comment by adriantintpilver** [comment] 2022-09-30 17:19
I can do this translation there is no problem, I just wanted to validate if you thought I could do it.

**Comment by breck7** [comment] 2022-09-30 17:21
got it @adriantintpilver ! there is no asking for permission here—only pull requests ;)

**Comment by SRS-WRKS** [comment] 2022-10-12 10:59
database/things/dad.pldb:
reference link https://sourceforge.net/projects/dadlang/ seems to refer to a C Sharp project while https://hopl.info/showlanguage.prx?exp=1945 talks about an ada dialect.

**Comment by adriantintpilver** [comment] 2022-10-12 15:26
Hi @SRS-WRKS , 
I see that and the information en dad.pldb is very scarce, but the language would seem real I found this --> https://www.proyectum.com/sistema/blog/disciplined-agile-delivery-dad/

I think you are right about dark basic, it sounds like a duplicate.

y go to fix this two things

**Comment by SRS-WRKS** [comment] 2022-11-15 04:53
Files 
`database/things/goedel.pldb ` and `database/things/godel.pldb` seem to be duplicates. Please note the slightly altered spellings.

**Comment by breck7** [comment] 2022-11-15 14:42
@SRS-WRKS can we create a new issue for these? (Or just submit commits with the corections). Thanks!

**Comment by adriantintpilver** [comment] 2022-11-15 18:52
> 

I would stay with Gödel and eliminar Goedel, but the problem is that Gödel is in German and when using the ö with umlaut you will never find it in the search engines, and they will probably create it again by not finding it. We could leave a joint name for both as "Gödel (Goedel)" so it can be found by searching for it in both languages.
The graphit is definitly duplicated and only keep one.

**Comment by SRS-WRKS** [comment] 2022-11-16 03:44
@adriantintpilver : pldn support key "aka". The alternative name could be provided as value to this key.

@breck7 Yes, but i cant delete files in the repository without discussion :).  The names are put here for discussion and after many days, if no one objects there would be deletion.

**Comment by adriantintpilver** [comment] 2022-11-16 14:28
Next I share with you the plan with all these fixes before making the pull request so that you can think about the issue since some duplicate or incorrect files are eliminated.

-. ALFRED: Link to Wikipedia, summary, release date and official site are added.

-. ALCOR: the extra text of wikipedia that did not appear in any way on the web is eliminated 

-. ALGOBOX: it is completed with translations from French and related links are added.

-. ALPHA: the two pages are merged, leaving all the information in one. (keeping alpha-programming-language.pldb and eliminating alpha.pldb)

-. BISTRO: was in triplicate and merged all into one --> bistro-programming-language, also checked hoot-smalltalk, in case it was also a duplicate, but it seems to be a bit different language based on BISTRO.(keeping bistro-programming-language.pldb and eliminating bistro.pldb and bistro-smalltalk.pldb)

-. CEL: the entry is deleted because there is no data on the internet about this language currently exists. (cel-programming-language.pldb is eliminated)

-. CIAO: The two CIAO pages ( ciao-programming-language and ciao) were merged into just one that seemed to have the most apt name --> ciao-programming-language (keeping ciao-programming-language.pldb and eliminating ciao.pldb)

-. CODE programming language: there is no such programming language, but at some point all languages are this, since they are all programming code languages, which makes it very difficult and confusing to search for it. On the other hand it would be a bit silly to put this name to a new language. Deleted the entry. (eliminating code-programming-language.pldb)

-. DAD: The language dad.pldb is edited with the correct information about Disciplined agile delivery (DAD)-. DARKBASIC: Merge the content of two duplicated darkbasic (darkbasic.pldb and dark-basic.pldb) in only one file darkbasic.pldb.(keeping darkbasic.pldb and eliminating dark-basic.pldb)

-. GRAPHIT: GraphIt and graph-it are duplicated, merge two and keep only graph-it.pldb (keeping graph-it.pldb and eliminating graphit.pldb)

-. Gödel: Gödel and Goedel are the same but Gödel is in German and does not appear in finds if you don't search with the umlaut "ö". keep only one with name Gödel (Goedel) and the aka = Goedel (keeping godel.pldb and eliminating goedel.pldb)

**Comment by adriantintpilver** [comment] 2022-11-16 15:38
i trying the aka field and i see this works in the "full text search" but doesn't work in the combo search. i think is good idea add the aka field to the combo search, what do you think?

**Comment by celtic-coder** [comment] 2022-11-16 16:09
Good work, Adrian (@adriantintpilver)! 👍

**Comment by SRS-WRKS** [comment] 2022-11-18 05:30
Files `database/things/hugo.pldb` and `database/things/hugo-programming-language.pldb` seem to be duplicates.

**Comment by adriantintpilver** [comment] 2022-11-18 20:48
I finally got through all these files I'm happy. It would be good to close this issue and create a new one when we have more duplicates or things to improve.

**Comment by celtic-coder** [comment] 2022-11-21 20:24
Main items have been taken care of in #322, can be closed.

**Closed by celtic-coder** 2022-11-21 20:24 UTC
Labels: goodFirstIssue
